### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by kubow** [Eugene-Mark/bigdata-file-viewer#12]
Hi Eugene,

I tried to run your java tool and I am getting this exception:

> Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	at org.eugene.App.main(App.java:13)
> Caused by: java.lang.ClassNotFoundException: javafx.application.Application
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	... 13 more
> 

Steps I proceeded with:

1. Download release 1.1.1 or latest 1.2.1 (both of them have same output for me)
2. invoke form command line: `java -jar BigdataFileViewer-1.1.1-SNAPSHOT-jar-with-dependencies.jar`

`cat /etc/lsb-release `

> DISTRIB_ID=ManjaroLinux
> DISTRIB_RELEASE=20.2.1
> DISTRIB_CODENAME=Nibia
> DISTRIB_DESCRIPTION="Manjaro Linux"

`java -version`

> openjdk version "1.8.0_265"
> OpenJDK Runtime Environment (build 1.8.0_265-b01)
> OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

Have you got any clue, what can cause this? It looks like I am missing some dependency, however all of them should be attached right?

Best Regards,
Kubow

**Comment by Eugene-Mark** [comment]
@kubow The main reason you catch this error info is because your local JDK doesn't have javafx bound. 
You might need to install javafx yourself and retry.
