### ISSUE TITLE
Instead hardcoded "\\"

### ISSUE THREAD

**Issue by sedzisz** [Eugene-Mark/bigdata-file-viewer#14]
Please use "File.separator" it will work on all OS not only on Windwos

https://github.com/Eugene-Mark/bigdata-file-viewer/blob/85be0bca8950adaca16d6704f03f992a08750da9/src/main/java/org/eugene/persistent/SqlliteWrapper.java#L15

```
$ java -jar BigdataFileViewer-1.2-SNAPSHOT-jar-with-dependencies.jar 
java.sql.SQLException: opening db: '/home/<user>\bdf.db': Permission denied
```

**Comment by Eugene-Mark** [comment]
@sedzisz Thanks for this information. Would you like to submit a PR to fix the issue? If sure, I will assign it to you.

**Comment by sedzisz** [comment]
> @sedzisz Thanks for this information. Would you like to submit a PR to fix the issue? If sure, I will assign it to you.

**Comment by sedzisz** [comment]
Sorry ofc :)
