### ISSUE TITLE
CSV delimiter.

### ISSUE THREAD

**Issue by sedzisz** [Eugene-Mark/bigdata-file-viewer#16]
Ability to define a delimiter for exported CSV files.

**Comment by Eugene-Mark** [comment]
@sedzisz It could be an improvement since for CSV, the delimiter could be other char. Thanks.

**Comment by Eugene-Mark** [comment]
@sedzisz Thanks for reporting this issue. It has been fixed by [this commit](https://github.com/Eugene-Mark/bigdata-file-viewer/commit/69f55460d2a73bcfc9580fe5c4dc49775752359d). Currently, there is an UI interface to set the delimiter used for output CSV file.
