### ISSUE TITLE
illegal character in column name

### ISSUE THREAD

**Issue by shawnjones253** [Eugene-Mark/bigdata-file-viewer#22]
![image](https://user-images.githubusercontent.com/13895057/120560981-9cfa9a00-c3b8-11eb-9ecb-d0290be3f988.png)

**Comment by Eugene-Mark** [comment]
@shawnjones253 Thanks for reporting it. Could you please let me know where I can download the sample file.

**Comment by shawnjones253** [comment]
@Eugene-Mark unfortunately the file i was working with has customer data in it -- but you should be able to reproduce this using any parquet file that uses `:` in the column name i imagine

**Comment by Eugene-Mark** [comment]
@shawnjones253 It's seems a limitation of AvroParquetReader per [this discussion](https://stackoverflow.com/questions/62085293/read-parquet-file-with-illegal-characters-apache-avro). Leave it as an limitation of Bigdata-File-Viewer.
