### ISSUE TITLE
Some Types not implemented

### ISSUE THREAD

**Issue by One-djey** [Eugene-Mark/bigdata-file-viewer#23]
I cannot read some of my parquet files, I have an error "INT96 not implemented". 
Should be great to know that all types are not readable yet.

**Comment by Eugene-Mark** [comment]
@One-djey Thanks for your feedback, please check this [closed issue](https://github.com/Eugene-Mark/bigdata-file-viewer/issues/4) for details, the INT96 is actually deprecated in Apache Parquet. We won't support this data type either.

**Comment by Eugene-Mark** [comment]
@One-djey Hi One-djey, the issue should have been fixed by [this commit](https://github.com/Eugene-Mark/bigdata-file-viewer/commit/68c3572d32ab72337042796c20849f5207c45cd6).
