### ISSUE TITLE
Error dialog window small and not scalable

### ISSUE THREAD

**Issue by rppein** [Eugene-Mark/bigdata-file-viewer#5]
Long error messages inside the tool cannot be read. The dialog window is rather small and cannot be scaled. The best bet to figure out what's happening is to take a look at the console output.

![Bildschirmfoto zu 2020-05-08 14-46-43](https://user-images.githubusercontent.com/10120316/81406928-c3f58680-913a-11ea-915a-ac3a7301639c.png)

The screenshot is actually related to issue #4.

**Comment by Eugene-Mark** [comment]
@rppein Thanks for this update. May I know the OS version and JDK version you used?

**Comment by Eugene-Mark** [comment]
@rppein Thanks for reporting the issue. It has been fixed by commit https://github.com/Eugene-Mark/bigdata-file-viewer/commit/ff9aa205b791716f6262a0f496102b1dc1bdb3f3
